name: myes
services:
  es:
    container_name: es
    image: my_es_ik:7.12.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - es-plugins:/usr/share/elasticsearch/plugins
    networks:
      - es-net
    privileged: true

  kibana:
    container_name: kibana
    image: docker.1ms.run/kibana:7.12.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    networks:
      - es-net
    ports:
      - "5601:5601"

volumes:
  es-data:
  es-plugins:

networks:
  es-net:
